import type { Rgb } from './palette';
import { nblRostersByTeamId } from '../data/nblRosters.data';
import { sanitizeOpeningRoster } from './rosterAdjustments';

// Real Czech NBL (Maxa NBL) season 2025/26: team metadata here; rosters generated by
// scripts/scrape-nbl-rosters.ts from nbl.basketball (scoutbasketball.com fallback).
export interface RealPlayerDef {
    firstName: string;
    lastName: string;
    position: 'PG' | 'SG' | 'SF' | 'PF' | 'C';
    heightCm: number | null;
    born: number | null;
    nationality: string | null;
    tier: number;
}

export interface TeamDef {
    id: string;
    abbr: string;
    name: string;
    shortName: string;
    city: string;
    primary: Rgb;
    secondary: Rgb;
    arenaName: string;
    arenaCapacity: number | null;
    tier: number;
    roster: RealPlayerDef[];
}

function hex(value: string): Rgb {
    return {
        r: Number.parseInt(value.slice(1, 3), 16),
        g: Number.parseInt(value.slice(3, 5), 16),
        b: Number.parseInt(value.slice(5, 7), 16),
    };
}

function nblTeam(
    id: string,
    abbr: string,
    name: string,
    shortName: string,
    city: string,
    primary: Rgb,
    secondary: Rgb,
    arenaName: string,
    arenaCapacity: number | null,
    tier: number,
): TeamDef {
    const roster = nblRostersByTeamId[id];
    if (!roster) {
        throw new Error(`league.ts: missing NBL roster for team '${id}' (run npm run rosters:scrape:nbl)`);
    }
    return {
        id,
        abbr,
        name,
        shortName,
        city,
        primary,
        secondary,
        arenaName,
        arenaCapacity,
        tier,
        roster: sanitizeOpeningRoster(id, roster),
    };
}

export const leagueConfig = Object.freeze({
    playersPerTeam: 12,
    roundRobinLegs: 2,
    startingSeasonYear: 2025,
    playoffs: Object.freeze({
        teams: 8,
        winsNeeded: Object.freeze([2, 3, 4]),
        thirdPlaceWinsNeeded: 2,
    }),
    teams: Object.freeze<TeamDef[]>([
        nblTeam('NYM', 'NYM', 'ERA Basketball Nymburk', 'Nymburk', 'Nymburk', hex('#1D1D1B'), hex('#E30613'), 'Sportovní centrum Nymburk', 1500, 5),
        nblTeam('PCE', 'PCE', 'BK KVIS Pardubice', 'Pardubice', 'Pardubice', hex('#C8102E'), hex('#FFFFFF'), 'Sportovní hala Pardubice', 1400, 4),
        nblTeam('BRN', 'BRN', 'PUMPA Basket Brno', 'Brno', 'Brno', hex('#003876'), hex('#E03A3E'), 'STAREZ Aréna Vodova', 2900, 4),
        nblTeam('UST', 'UST', 'SLUNETA Ústí nad Labem', 'Ústí n. L.', 'Ústí nad Labem', hex('#FDB913'), hex('#005BAA'), 'Sportovní hala Sluneta', 1600, 3),
        nblTeam('OPA', 'OPA', 'BK Opava', 'Opava', 'Opava', hex('#FFD200'), hex('#003DA5'), 'Víceúčelová hala Opava', 2154, 3),
        nblTeam('PIS', 'PIS', 'Sršni Photomate Písek', 'Písek', 'Písek', hex('#FFCC00'), hex('#1A1A1A'), 'Sportovní hala Písek', null, 3),
        nblTeam('DEC', 'DEC', 'BK ARMEX ENERGY Děčín', 'Děčín', 'Děčín', hex('#0057B8'), hex('#FFFFFF'), 'Sportovní hala Děčín', 1047, 3),
        nblTeam('OST', 'OST', 'NH Ostrava', 'Ostrava', 'Ostrava', hex('#0072CE'), hex('#FFFFFF'), 'Sportovní hala NH Ostrava', 1200, 2),
        nblTeam('OLO', 'OLO', 'BK Olomoucko', 'Olomoucko', 'Olomouc', hex('#1E5AA8'), hex('#FFFFFF'), 'Sportovní hala Olomouc', 2000, 2),
        nblTeam('USK', 'USK', 'USK Praha', 'USK Praha', 'Praha', hex('#0D4F9E'), hex('#FFFFFF'), 'Sportovní hala USK', 1065, 2),
        nblTeam('SLA', 'SLA', 'SK Slavia Praha ERA NBK', 'Slavia Praha', 'Praha', hex('#E4002B'), hex('#FFFFFF'), 'Sportovní hala Slavia', 1980, 2),
        nblTeam('HKR', 'HKR', 'BK GAPA Hradec Králové', 'Hradec Král.', 'Hradec Králové', hex('#1A1A1A'), hex('#F47920'), 'Sportovní hala HK', 700, 1),
    ]),
});

export type LeagueConfig = typeof leagueConfig;
