/**
 * Builds BCL player valuation data for the in-game scout table and CSV export.
 * Run: npm run bcl:valuations
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createNewGame } from '../src/core/game.ts';
import { generateBclClubs } from '../src/core/league/generate.ts';
import { baseSalary, contractDemand, transferValue } from '../src/core/market.ts';
import { overallRating } from '../src/core/model/types.ts';
import type { Player } from '../src/core/model/types.ts';
import { createRng } from '../src/core/rng.ts';
import { testConfig as config } from '../tests/helpers.ts';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const CSV_PATH = join(ROOT, 'public', 'data', 'bcl-valuations.csv');
const DATA_PATH = join(ROOT, 'src', 'data', 'bclValuations.data.ts');

const SEED = 99;
const SEASON_YEAR = 2026;

export interface BclValuationRow {
    teamId: string;
    club: string;
    tier: number;
    playerId: string;
    name: string;
    position: string;
    age: number;
    ovr: number;
    potential: number;
    source: 'real' | 'generated';
    estSalary: number;
    estDemand: number;
    estValue: number;
}

function hypotheticalTransferValue(player: Player): number {
    const ovr = overallRating(player.attributes);
    const temp: Player = {
        ...player,
        contract: { salary: baseSalary(ovr, config.economy), yearsLeft: 2 },
    };
    return transferValue(temp, config.market, config.economy);
}

function buildRows(): BclValuationRow[] {
    const state = createNewGame(config, 42, 'NYM');
    generateBclClubs(state, config.bcl, config.balance, config.names, SEASON_YEAR, createRng(SEED));

    const rows: BclValuationRow[] = [];
    for (const teamDef of config.bcl.teams.filter((t) => !t.nblTeamId)) {
        const team = state.teams[teamDef.id];
        if (!team) {
            continue;
        }
        for (const playerId of team.playerIds) {
            const player = state.players[playerId];
            if (!player) {
                continue;
            }
            const ovr = overallRating(player.attributes);
            const isReal = teamDef.roster.some(
                (r) => r.firstName === player.firstName && r.lastName === player.lastName,
            );
            rows.push({
                teamId: teamDef.id,
                club: teamDef.shortName,
                tier: teamDef.tier,
                playerId: player.id,
                name: `${player.firstName} ${player.lastName}`,
                position: player.position,
                age: player.age,
                ovr,
                potential: player.potential,
                source: isReal ? 'real' : 'generated',
                estSalary: baseSalary(ovr, config.economy),
                estDemand: contractDemand(state, player, config.market, config.economy),
                estValue: hypotheticalTransferValue(player),
            });
        }
    }
    rows.sort((a, b) => b.ovr - a.ovr || a.club.localeCompare(b.club) || a.name.localeCompare(b.name));
    return rows;
}

function csvEscape(value: string | number): string {
    const text = String(value);
    if (text.includes(',') || text.includes('"') || text.includes('\n')) {
        return `"${text.replace(/"/g, '""')}"`;
    }
    return text;
}

function toCsv(rows: BclValuationRow[]): string {
    const header = [
        'team_id',
        'club',
        'tier',
        'player_id',
        'name',
        'position',
        'age',
        'ovr',
        'potential',
        'source',
        'est_salary_czk',
        'est_demand_czk',
        'est_value_czk',
    ];
    const lines = [header.join(',')];
    for (const row of rows) {
        lines.push(
            [
                row.teamId,
                row.club,
                row.tier,
                row.playerId,
                row.name,
                row.position,
                row.age,
                row.ovr,
                row.potential,
                row.source,
                row.estSalary,
                row.estDemand,
                row.estValue,
            ]
                .map(csvEscape)
                .join(','),
        );
    }
    return `${lines.join('\n')}\n`;
}

function toDataModule(rows: BclValuationRow[]): string {
    return `// Generated by scripts/generate-bcl-valuations.ts — do not edit by hand.
import type { BclValuationRow } from './bclValuations';

export const bclValuationSeed = ${SEED};
export const bclValuationSeasonYear = ${SEASON_YEAR};

export const bclValuationsData: readonly BclValuationRow[] = ${JSON.stringify(rows, null, 4)} as const;
`;
}

function main(): void {
    const rows = buildRows();
    mkdirSync(dirname(CSV_PATH), { recursive: true });
    writeFileSync(CSV_PATH, toCsv(rows));
    writeFileSync(DATA_PATH, toDataModule(rows));
    console.log(`Wrote ${rows.length} rows to ${CSV_PATH}`);
    console.log(`Wrote ${DATA_PATH}`);
}

main();
