// Generated by scripts/scrape-nbl-rosters.ts — do not edit by hand.
import type { RealPlayerDef } from '../config/league';

/** Real Czech NBL rosters (2025-26), sourced from nbl.basketball / scoutbasketball.com. */
export const nblRostersByTeamId: Record<string, readonly RealPlayerDef[]> = {
    "NYM": [
        {
            "firstName": "Matěj",
            "lastName": "Svoboda",
            "position": "SF",
            "tier": 5,
            "heightCm": null,
            "born": 1996,
            "nationality": "CZE"
        },
        {
            "firstName": "Martin",
            "lastName": "Kříž",
            "position": "PF",
            "tier": 5,
            "heightCm": null,
            "born": 1993,
            "nationality": "CZE"
        },
        {
            "firstName": "Jaquan",
            "lastName": "Lawrence",
            "position": "SF",
            "tier": 4,
            "heightCm": null,
            "born": 1999,
            "nationality": "USA"
        },
        {
            "firstName": "František",
            "lastName": "Rylich",
            "position": "SF",
            "tier": 4,
            "heightCm": null,
            "born": 2002,
            "nationality": "CZE"
        },
        {
            "firstName": "Jaromír",
            "lastName": "Bohačík",
            "position": "SG",
            "tier": 4,
            "heightCm": null,
            "born": 1992,
            "nationality": "CZE"
        },
        {
            "firstName": "Ondřej",
            "lastName": "Sehnal",
            "position": "PG",
            "tier": 3,
            "heightCm": null,
            "born": 1997,
            "nationality": "CZE"
        },
        {
            "firstName": "Vojtěch",
            "lastName": "Hruban",
            "position": "SF",
            "tier": 3,
            "heightCm": null,
            "born": 1989,
            "nationality": "CZE"
        },
        {
            "firstName": "Jay",
            "lastName": "Shumate",
            "position": "PF",
            "tier": 3,
            "heightCm": null,
            "born": 1999,
            "nationality": "USA"
        },
        {
            "firstName": "Marcus Armani Santos -",
            "lastName": "Silva",
            "position": "SF",
            "tier": 3,
            "heightCm": null,
            "born": 1997,
            "nationality": "USA"
        },
        {
            "firstName": "Sir Jabari",
            "lastName": "Rice",
            "position": "SF",
            "tier": 3,
            "heightCm": null,
            "born": 1998,
            "nationality": "USA"
        },
        {
            "firstName": "Tony",
            "lastName": "Perkins",
            "position": "SF",
            "tier": 3,
            "heightCm": null,
            "born": 2001,
            "nationality": "USA"
        },
        {
            "firstName": "Goran",
            "lastName": "Filipovic",
            "position": "SF",
            "tier": 3,
            "heightCm": null,
            "born": 1996,
            "nationality": "CRO"
        }
    ],
    "PCE": [
        {
            "firstName": "Jamonda Roshawn",
            "lastName": "Bryant",
            "position": "SF",
            "tier": 5,
            "heightCm": null,
            "born": 2000,
            "nationality": "USA"
        },
        {
            "firstName": "Kamil",
            "lastName": "Švrdlík",
            "position": "C",
            "tier": 4,
            "heightCm": null,
            "born": 1986,
            "nationality": "CZE"
        },
        {
            "firstName": "Jakub",
            "lastName": "Tůma",
            "position": "PG",
            "tier": 3,
            "heightCm": null,
            "born": 1998,
            "nationality": "CZE"
        },
        {
            "firstName": "Ryan Everett",
            "lastName": "Moffatt",
            "position": "SF",
            "tier": 3,
            "heightCm": null,
            "born": 2000,
            "nationality": "USA"
        },
        {
            "firstName": "Luboš",
            "lastName": "Kovář",
            "position": "PF",
            "tier": 3,
            "heightCm": null,
            "born": 2000,
            "nationality": "CZE"
        },
        {
            "firstName": "Robert Lee",
            "lastName": "Bonham",
            "position": "SF",
            "tier": 2,
            "heightCm": null,
            "born": 2002,
            "nationality": "USA"
        },
        {
            "firstName": "Adam",
            "lastName": "Lukeš",
            "position": "PG",
            "tier": 2,
            "heightCm": null,
            "born": 2004,
            "nationality": "CZE"
        },
        {
            "firstName": "Zed Jackson",
            "lastName": "Key",
            "position": "SF",
            "tier": 2,
            "heightCm": null,
            "born": 2002,
            "nationality": "USA"
        },
        {
            "firstName": "Martin",
            "lastName": "Nábělek",
            "position": "PG",
            "tier": 2,
            "heightCm": null,
            "born": 1998,
            "nationality": "CZE"
        },
        {
            "firstName": "Jacob Nicholas Evans",
            "lastName": "III",
            "position": "SG",
            "tier": 2,
            "heightCm": null,
            "born": 1997,
            "nationality": "USA"
        },
        {
            "firstName": "Michal",
            "lastName": "Svojanovský",
            "position": "SF",
            "tier": 2,
            "heightCm": null,
            "born": 2001,
            "nationality": "CZE"
        },
        {
            "firstName": "Petr",
            "lastName": "Šťovíček",
            "position": "PF",
            "tier": 2,
            "heightCm": null,
            "born": 2004,
            "nationality": "CZE"
        }
    ],
    "BRN": [
        {
            "firstName": "Šimon",
            "lastName": "Svoboda",
            "position": "SF",
            "tier": 5,
            "heightCm": null,
            "born": 2004,
            "nationality": "CZE"
        },
        {
            "firstName": "Milan Tomáš",
            "lastName": "Stráněl",
            "position": "PF",
            "tier": 4,
            "heightCm": null,
            "born": 2005,
            "nationality": "CZE"
        },
        {
            "firstName": "Radek",
            "lastName": "Farský",
            "position": "SG",
            "tier": 3,
            "heightCm": null,
            "born": 1999,
            "nationality": "CZE"
        },
        {
            "firstName": "Adam",
            "lastName": "Kejval",
            "position": "C",
            "tier": 3,
            "heightCm": null,
            "born": 2002,
            "nationality": "CZE"
        },
        {
            "firstName": "Viktor",
            "lastName": "Půlpán",
            "position": "PG",
            "tier": 3,
            "heightCm": null,
            "born": 1996,
            "nationality": "CZE"
        },
        {
            "firstName": "Kevin Chukwuemeka",
            "lastName": "Kalu",
            "position": "SF",
            "tier": 2,
            "heightCm": null,
            "born": 2003,
            "nationality": "USA"
        },
        {
            "firstName": "Tomáš",
            "lastName": "Jansa",
            "position": "PG",
            "tier": 2,
            "heightCm": null,
            "born": 2002,
            "nationality": "CZE"
        },
        {
            "firstName": "David",
            "lastName": "Jelínek",
            "position": "SF",
            "tier": 2,
            "heightCm": null,
            "born": 1990,
            "nationality": "CZE"
        },
        {
            "firstName": "Matěj",
            "lastName": "Rychtecký",
            "position": "SG",
            "tier": 2,
            "heightCm": null,
            "born": 2004,
            "nationality": "CZE"
        },
        {
            "firstName": "Petr",
            "lastName": "Křivánek",
            "position": "PG",
            "tier": 2,
            "heightCm": null,
            "born": 2003,
            "nationality": "CZE"
        },
        {
            "firstName": "Ryker Broden",
            "lastName": "Cisarik",
            "position": "SF",
            "tier": 2,
            "heightCm": null,
            "born": 2002,
            "nationality": "USA"
        },
        {
            "firstName": "Tevin Thomas",
            "lastName": "Olison",
            "position": "SF",
            "tier": 2,
            "heightCm": null,
            "born": 1998,
            "nationality": "USA"
        }
    ],
    "UST": [
        {
            "firstName": "Jayhlon",
            "lastName": "Young",
            "position": "SF",
            "tier": 4,
            "heightCm": null,
            "born": 2001,
            "nationality": "USA"
        },
        {
            "firstName": "Nicholas",
            "lastName": "Johnson",
            "position": "SF",
            "tier": 3,
            "heightCm": null,
            "born": 2001,
            "nationality": "USA"
        },
        {
            "firstName": "Ladislav",
            "lastName": "Pecka",
            "position": "PF",
            "tier": 2,
            "heightCm": null,
            "born": 1991,
            "nationality": "CZE"
        },
        {
            "firstName": "Filip",
            "lastName": "Kábrt",
            "position": "SF",
            "tier": 2,
            "heightCm": null,
            "born": 2002,
            "nationality": "CZE"
        },
        {
            "firstName": "Josef",
            "lastName": "Potoček",
            "position": "SF",
            "tier": 2,
            "heightCm": null,
            "born": 1996,
            "nationality": "CZE"
        },
        {
            "firstName": "Adam",
            "lastName": "Pecháček",
            "position": "C",
            "tier": 1,
            "heightCm": null,
            "born": 1995,
            "nationality": "CZE"
        },
        {
            "firstName": "Tomáš",
            "lastName": "Vyoral",
            "position": "PG",
            "tier": 1,
            "heightCm": null,
            "born": 1992,
            "nationality": "CZE"
        },
        {
            "firstName": "David",
            "lastName": "Žikla",
            "position": "PF",
            "tier": 1,
            "heightCm": null,
            "born": 1998,
            "nationality": "CZE"
        },
        {
            "firstName": "Isaac",
            "lastName": "Davidson",
            "position": "SF",
            "tier": 1,
            "heightCm": null,
            "born": 1997,
            "nationality": "NZL"
        },
        {
            "firstName": "Kimani",
            "lastName": "Lawrence",
            "position": "SF",
            "tier": 1,
            "heightCm": null,
            "born": 1998,
            "nationality": "USA"
        },
        {
            "firstName": "Petr",
            "lastName": "Krupka",
            "position": "SF",
            "tier": 1,
            "heightCm": null,
            "born": 2003,
            "nationality": "CZE"
        },
        {
            "firstName": "J´D Derryus",
            "lastName": "Eatmon",
            "position": "SF",
            "tier": 1,
            "heightCm": null,
            "born": 2001,
            "nationality": "USA"
        }
    ],
    "OPA": [
        {
            "firstName": "Jan",
            "lastName": "Švandrlík",
            "position": "SF",
            "tier": 4,
            "heightCm": null,
            "born": 1994,
            "nationality": "CZE"
        },
        {
            "firstName": "Clevon Brown",
            "lastName": "Jr",
            "position": "SF",
            "tier": 3,
            "heightCm": null,
            "born": 1998,
            "nationality": "USA"
        },
        {
            "firstName": "Jakub",
            "lastName": "Šiřina",
            "position": "PG",
            "tier": 2,
            "heightCm": null,
            "born": 1987,
            "nationality": "CZE"
        },
        {
            "firstName": "Šimon",
            "lastName": "Puršl",
            "position": "C",
            "tier": 2,
            "heightCm": null,
            "born": 1997,
            "nationality": "CZE"
        },
        {
            "firstName": "Jakub",
            "lastName": "Slavík",
            "position": "SF",
            "tier": 2,
            "heightCm": null,
            "born": 1999,
            "nationality": "CZE"
        },
        {
            "firstName": "Wesley Lavon Person",
            "lastName": "Jr",
            "position": "SF",
            "tier": 1,
            "heightCm": null,
            "born": 1995,
            "nationality": "USA"
        },
        {
            "firstName": "Kryštof",
            "lastName": "Kavan",
            "position": "SG",
            "tier": 1,
            "heightCm": null,
            "born": 2002,
            "nationality": "CZE"
        },
        {
            "firstName": "Marek",
            "lastName": "Vyroubal",
            "position": "PG",
            "tier": 1,
            "heightCm": null,
            "born": 2001,
            "nationality": "CZE"
        },
        {
            "firstName": "Filip",
            "lastName": "Zbránek",
            "position": "SF",
            "tier": 1,
            "heightCm": null,
            "born": 1990,
            "nationality": "CZE"
        },
        {
            "firstName": "David",
            "lastName": "Motyčka",
            "position": "PF",
            "tier": 1,
            "heightCm": null,
            "born": 2006,
            "nationality": "CZE"
        },
        {
            "firstName": "František",
            "lastName": "Váňa",
            "position": "SF",
            "tier": 1,
            "heightCm": null,
            "born": 1998,
            "nationality": "CZE"
        },
        {
            "firstName": "Isaiah John",
            "lastName": "Gray",
            "position": "SF",
            "tier": 1,
            "heightCm": null,
            "born": 2001,
            "nationality": "USA"
        }
    ],
    "PIS": [
        {
            "firstName": "Josef",
            "lastName": "Svoboda",
            "position": "SG",
            "tier": 4,
            "heightCm": null,
            "born": 2005,
            "nationality": "CZE"
        },
        {
            "firstName": "Jan",
            "lastName": "Karlovský",
            "position": "PF",
            "tier": 3,
            "heightCm": null,
            "born": 1999,
            "nationality": "CZE"
        },
        {
            "firstName": "Johan",
            "lastName": "Haiblík",
            "position": "PF",
            "tier": 2,
            "heightCm": null,
            "born": 2000,
            "nationality": "CZE"
        },
        {
            "firstName": "Michal",
            "lastName": "Kozák",
            "position": "PF",
            "tier": 2,
            "heightCm": null,
            "born": 1998,
            "nationality": "CZE"
        },
        {
            "firstName": "Petr",
            "lastName": "Šlechta",
            "position": "SF",
            "tier": 2,
            "heightCm": null,
            "born": 1995,
            "nationality": "CZE"
        },
        {
            "firstName": "Matěj",
            "lastName": "Burda",
            "position": "PG",
            "tier": 1,
            "heightCm": null,
            "born": 2001,
            "nationality": "CZE"
        },
        {
            "firstName": "Kevin",
            "lastName": "Týml",
            "position": "SF",
            "tier": 1,
            "heightCm": null,
            "born": 2001,
            "nationality": "CZE"
        },
        {
            "firstName": "František",
            "lastName": "Suchánek",
            "position": "SF",
            "tier": 1,
            "heightCm": null,
            "born": 2006,
            "nationality": "CZE"
        },
        {
            "firstName": "Vojtěch",
            "lastName": "Sýkora",
            "position": "PG",
            "tier": 1,
            "heightCm": null,
            "born": 2001,
            "nationality": "CZE"
        },
        {
            "firstName": "Jakub",
            "lastName": "Zvolánek",
            "position": "PG",
            "tier": 1,
            "heightCm": null,
            "born": 2005,
            "nationality": "CZE"
        },
        {
            "firstName": "Martin",
            "lastName": "Svoboda",
            "position": "PF",
            "tier": 1,
            "heightCm": null,
            "born": 2001,
            "nationality": "CZE"
        },
        {
            "firstName": "Jakub",
            "lastName": "Šimonek",
            "position": "PG",
            "tier": 1,
            "heightCm": null,
            "born": 2006,
            "nationality": "CZE"
        }
    ],
    "DEC": [
        {
            "firstName": "Filip",
            "lastName": "Kroutil",
            "position": "SF",
            "tier": 4,
            "heightCm": null,
            "born": 1996,
            "nationality": "CZE"
        },
        {
            "firstName": "Jaden Bryce",
            "lastName": "Dewar",
            "position": "SF",
            "tier": 3,
            "heightCm": null,
            "born": 1999,
            "nationality": "CAN"
        },
        {
            "firstName": "Lukáš",
            "lastName": "Feštr",
            "position": "PG",
            "tier": 2,
            "heightCm": null,
            "born": 1994,
            "nationality": "CZE"
        },
        {
            "firstName": "Tomáš",
            "lastName": "Pomikálek",
            "position": "SF",
            "tier": 2,
            "heightCm": null,
            "born": 1989,
            "nationality": "CZE"
        },
        {
            "firstName": "Maksim",
            "lastName": "Šturanović",
            "position": "C",
            "tier": 2,
            "heightCm": null,
            "born": 1988,
            "nationality": "SRB"
        },
        {
            "firstName": "Jan",
            "lastName": "Štěrba",
            "position": "SF",
            "tier": 1,
            "heightCm": null,
            "born": 1995,
            "nationality": "CZE"
        },
        {
            "firstName": "Dashawn Calvin",
            "lastName": "Davis",
            "position": "SF",
            "tier": 1,
            "heightCm": null,
            "born": 2000,
            "nationality": "USA"
        },
        {
            "firstName": "Josef",
            "lastName": "Gabriel",
            "position": "SF",
            "tier": 1,
            "heightCm": null,
            "born": 2006,
            "nationality": "CZE"
        },
        {
            "firstName": "Oliver",
            "lastName": "Žižka",
            "position": "C",
            "tier": 1,
            "heightCm": null,
            "born": 2005,
            "nationality": "CZE"
        },
        {
            "firstName": "Marek",
            "lastName": "Houška",
            "position": "SF",
            "tier": 1,
            "heightCm": null,
            "born": 2009,
            "nationality": "CZE"
        },
        {
            "firstName": "Posh",
            "lastName": "Alexander",
            "position": "SF",
            "tier": 1,
            "heightCm": null,
            "born": 2001,
            "nationality": "USA"
        },
        {
            "firstName": "Michal",
            "lastName": "Grill",
            "position": "SF",
            "tier": 1,
            "heightCm": null,
            "born": 2006,
            "nationality": "CZE"
        }
    ],
    "OST": [
        {
            "firstName": "Lukáš",
            "lastName": "Palyza",
            "position": "SF",
            "tier": 3,
            "heightCm": null,
            "born": 1989,
            "nationality": "CZE"
        },
        {
            "firstName": "Dominik",
            "lastName": "Heinzl",
            "position": "C",
            "tier": 2,
            "heightCm": null,
            "born": 1995,
            "nationality": "CZE"
        },
        {
            "firstName": "Adam",
            "lastName": "Číž",
            "position": "PG",
            "tier": 1,
            "heightCm": null,
            "born": 1991,
            "nationality": "CZE"
        },
        {
            "firstName": "Mikuláš",
            "lastName": "Čank",
            "position": "PG",
            "tier": 1,
            "heightCm": null,
            "born": 2006,
            "nationality": "CZE"
        },
        {
            "firstName": "Michal",
            "lastName": "Svoboda",
            "position": "SF",
            "tier": 1,
            "heightCm": null,
            "born": 1999,
            "nationality": "CZE"
        },
        {
            "firstName": "Matěj",
            "lastName": "Snopek",
            "position": "SG",
            "tier": 1,
            "heightCm": null,
            "born": 2000,
            "nationality": "CZE"
        },
        {
            "firstName": "Keenon",
            "lastName": "Cole",
            "position": "SF",
            "tier": 1,
            "heightCm": null,
            "born": 2000,
            "nationality": "USA"
        },
        {
            "firstName": "Elias",
            "lastName": "Cato",
            "position": "SF",
            "tier": 1,
            "heightCm": null,
            "born": 2001,
            "nationality": "AUS"
        },
        {
            "firstName": "Samuel Dennis",
            "lastName": "Godwin",
            "position": "SF",
            "tier": 1,
            "heightCm": null,
            "born": 2001,
            "nationality": "USA"
        },
        {
            "firstName": "Pavel",
            "lastName": "Novák",
            "position": "SF",
            "tier": 1,
            "heightCm": null,
            "born": 2002,
            "nationality": "CZE"
        },
        {
            "firstName": "Lynn Terence",
            "lastName": "Greer",
            "position": "SF",
            "tier": 1,
            "heightCm": null,
            "born": 2002,
            "nationality": "USA"
        },
        {
            "firstName": "Matyáš",
            "lastName": "Janů",
            "position": "SF",
            "tier": 1,
            "heightCm": null,
            "born": 2002,
            "nationality": "CZE"
        }
    ],
    "OLO": [
        {
            "firstName": "Adam",
            "lastName": "Goga",
            "position": "PG",
            "tier": 3,
            "heightCm": null,
            "born": 1997,
            "nationality": "CZE"
        },
        {
            "firstName": "Kyler",
            "lastName": "Filewich",
            "position": "SF",
            "tier": 2,
            "heightCm": null,
            "born": 2001,
            "nationality": "CAN"
        },
        {
            "firstName": "Ondřej",
            "lastName": "Šiška",
            "position": "SF",
            "tier": 1,
            "heightCm": null,
            "born": 1993,
            "nationality": "CZE"
        },
        {
            "firstName": "Dominik",
            "lastName": "Žák",
            "position": "PF",
            "tier": 1,
            "heightCm": null,
            "born": 2001,
            "nationality": "CZE"
        },
        {
            "firstName": "Marek Ayers",
            "lastName": "Nelson",
            "position": "SF",
            "tier": 1,
            "heightCm": null,
            "born": 1999,
            "nationality": "USA"
        },
        {
            "firstName": "Jonathan Leonard",
            "lastName": "Andre",
            "position": "SF",
            "tier": 1,
            "heightCm": null,
            "born": 1997,
            "nationality": "USA"
        },
        {
            "firstName": "Jordan",
            "lastName": "Oupoh",
            "position": "SF",
            "tier": 1,
            "heightCm": null,
            "born": 2005,
            "nationality": "CZE"
        },
        {
            "firstName": "Miroslav",
            "lastName": "Kvapil",
            "position": "PF",
            "tier": 1,
            "heightCm": null,
            "born": 1993,
            "nationality": "CZE"
        },
        {
            "firstName": "Kobe",
            "lastName": "Elvis",
            "position": "SF",
            "tier": 1,
            "heightCm": null,
            "born": 2001,
            "nationality": "CAN"
        },
        {
            "firstName": "Jiří",
            "lastName": "Svojanovský",
            "position": "SF",
            "tier": 1,
            "heightCm": null,
            "born": 2002,
            "nationality": "CZE"
        },
        {
            "firstName": "Jaren Jamir",
            "lastName": "Holmes",
            "position": "SF",
            "tier": 1,
            "heightCm": null,
            "born": 1998,
            "nationality": "USA"
        },
        {
            "firstName": "Šimon",
            "lastName": "Čermák",
            "position": "SF",
            "tier": 1,
            "heightCm": null,
            "born": 2006,
            "nationality": "CZE"
        }
    ],
    "USK": [
        {
            "firstName": "Matěj",
            "lastName": "Šafařík",
            "position": "PG",
            "tier": 3,
            "heightCm": null,
            "born": 2003,
            "nationality": "CZE"
        },
        {
            "firstName": "Dalibor",
            "lastName": "Vlk",
            "position": "SF",
            "tier": 2,
            "heightCm": null,
            "born": 2002,
            "nationality": "CZE"
        },
        {
            "firstName": "Touko",
            "lastName": "Tainamo",
            "position": "SF",
            "tier": 1,
            "heightCm": null,
            "born": 2001,
            "nationality": "FIN"
        },
        {
            "firstName": "Ondřej",
            "lastName": "Švec",
            "position": "PG",
            "tier": 1,
            "heightCm": null,
            "born": 2003,
            "nationality": "CZE"
        },
        {
            "firstName": "Cortesao Joao",
            "lastName": "Eduardo",
            "position": "PF",
            "tier": 1,
            "heightCm": null,
            "born": 2002,
            "nationality": "CZE"
        },
        {
            "firstName": "Jalen Terence",
            "lastName": "Montgomery",
            "position": "SF",
            "tier": 1,
            "heightCm": null,
            "born": 2001,
            "nationality": "USA"
        },
        {
            "firstName": "František",
            "lastName": "Fuxa",
            "position": "C",
            "tier": 1,
            "heightCm": null,
            "born": 2000,
            "nationality": "CZE"
        },
        {
            "firstName": "Jakub",
            "lastName": "Soldán",
            "position": "SF",
            "tier": 1,
            "heightCm": null,
            "born": 2006,
            "nationality": "CZE"
        },
        {
            "firstName": "Lukáš",
            "lastName": "Dejmek",
            "position": "SF",
            "tier": 1,
            "heightCm": null,
            "born": 2006,
            "nationality": "CZE"
        },
        {
            "firstName": "Terry Henderson",
            "lastName": "Jr.",
            "position": "SF",
            "tier": 1,
            "heightCm": null,
            "born": 1994,
            "nationality": "USA"
        },
        {
            "firstName": "Samuel",
            "lastName": "Macht",
            "position": "SF",
            "tier": 1,
            "heightCm": null,
            "born": 2006,
            "nationality": "CZE"
        },
        {
            "firstName": "Tomáš",
            "lastName": "Palas",
            "position": "SF",
            "tier": 1,
            "heightCm": null,
            "born": 2004,
            "nationality": "CZE"
        }
    ],
    "SLA": [
        {
            "firstName": "Matyáš",
            "lastName": "Ježek",
            "position": "SF",
            "tier": 3,
            "heightCm": null,
            "born": 2005,
            "nationality": "CZE"
        },
        {
            "firstName": "Jan",
            "lastName": "Matušík",
            "position": "SF",
            "tier": 2,
            "heightCm": null,
            "born": 2006,
            "nationality": "CZE"
        },
        {
            "firstName": "David",
            "lastName": "Böhm",
            "position": "PF",
            "tier": 1,
            "heightCm": null,
            "born": 2001,
            "nationality": "CZE"
        },
        {
            "firstName": "Rubin Patrick",
            "lastName": "Jones",
            "position": "SF",
            "tier": 1,
            "heightCm": null,
            "born": 2001,
            "nationality": "USA"
        },
        {
            "firstName": "Radovan",
            "lastName": "Mrázek",
            "position": "PG",
            "tier": 1,
            "heightCm": null,
            "born": 2004,
            "nationality": "CZE"
        },
        {
            "firstName": "Matěj",
            "lastName": "Dáňa",
            "position": "SG",
            "tier": 1,
            "heightCm": null,
            "born": 2003,
            "nationality": "CZE"
        },
        {
            "firstName": "Nikolaos",
            "lastName": "Noumeros",
            "position": "SF",
            "tier": 1,
            "heightCm": null,
            "born": 2001,
            "nationality": "CZE"
        },
        {
            "firstName": "Petr",
            "lastName": "Macháč",
            "position": "PF",
            "tier": 1,
            "heightCm": null,
            "born": 1999,
            "nationality": "CZE"
        },
        {
            "firstName": "Meshack Wandja",
            "lastName": "Lufile",
            "position": "SF",
            "tier": 1,
            "heightCm": null,
            "born": 1992,
            "nationality": "CAN"
        },
        {
            "firstName": "Radek",
            "lastName": "Pumprla",
            "position": "SG",
            "tier": 1,
            "heightCm": null,
            "born": 1995,
            "nationality": "CZE"
        },
        {
            "firstName": "Tyrel Devonte",
            "lastName": "Bladen",
            "position": "SF",
            "tier": 1,
            "heightCm": null,
            "born": 2001,
            "nationality": "USA"
        },
        {
            "firstName": "Vojtěch",
            "lastName": "Zeithammer",
            "position": "SF",
            "tier": 1,
            "heightCm": null,
            "born": 2005,
            "nationality": "CZE"
        }
    ],
    "HKR": [
        {
            "firstName": "Martin",
            "lastName": "Roub",
            "position": "C",
            "tier": 2,
            "heightCm": null,
            "born": 1997,
            "nationality": "CZE"
        },
        {
            "firstName": "Tomáš",
            "lastName": "Merta",
            "position": "SF",
            "tier": 1,
            "heightCm": null,
            "born": 2001,
            "nationality": "CZE"
        },
        {
            "firstName": "David",
            "lastName": "Škranc",
            "position": "SF",
            "tier": 1,
            "heightCm": null,
            "born": 1996,
            "nationality": "CZE"
        },
        {
            "firstName": "Kareem Lamonte",
            "lastName": "Brewton",
            "position": "SF",
            "tier": 1,
            "heightCm": null,
            "born": 1995,
            "nationality": "USA"
        },
        {
            "firstName": "Kameron Jamal",
            "lastName": "Chatman",
            "position": "PF",
            "tier": 1,
            "heightCm": null,
            "born": 1996,
            "nationality": "USA"
        },
        {
            "firstName": "Jan",
            "lastName": "Bubeníček",
            "position": "SG",
            "tier": 1,
            "heightCm": null,
            "born": 2005,
            "nationality": "CZE"
        },
        {
            "firstName": "Tomáš",
            "lastName": "Dvořák",
            "position": "PG",
            "tier": 1,
            "heightCm": null,
            "born": 2002,
            "nationality": "CZE"
        },
        {
            "firstName": "Austin Calvin",
            "lastName": "Johnson",
            "position": "SF",
            "tier": 1,
            "heightCm": null,
            "born": 1999,
            "nationality": "USA"
        },
        {
            "firstName": "Lassi Paavo Verner",
            "lastName": "Nikkarinen",
            "position": "SF",
            "tier": 1,
            "heightCm": null,
            "born": 1997,
            "nationality": "FIN"
        },
        {
            "firstName": "Tomáš",
            "lastName": "Tkadlec",
            "position": "SF",
            "tier": 1,
            "heightCm": null,
            "born": 1999,
            "nationality": "CZE"
        },
        {
            "firstName": "Alessandro",
            "lastName": "Petric",
            "position": "SF",
            "tier": 1,
            "heightCm": null,
            "born": 1998,
            "nationality": "CZE"
        },
        {
            "firstName": "Matija",
            "lastName": "Popović",
            "position": "SF",
            "tier": 1,
            "heightCm": null,
            "born": 1996,
            "nationality": "SRB"
        }
    ]
} as const;
